inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'node_modules/**/*'

GitHub/RailsControllerRenderPathsExist:
  Enabled: false

